server:
  port: 8181
spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/migration/schema.yml, classpath:db/migration/data.yml
    default-schema: public
  datasource:
    url: jdbc:postgresql://localhost:5555/bank_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  jwt:
    secret-key: "91ebaabcb0adf86142ae9cafa869a8fc173ad3151b7256da752e1b20104459cf"
    expiration: 86400000


  #- Включить Swagger UI.
