databaseChangeLog:
  - changeSet:
      id: 1
      author: romreign
      changes:
        - createTable:
            tableName: roles
            columns:
              - column:
                  name: id
                  type: BIGINT
                  constraints:
                    primaryKey: true
                    nullable: false
                    autoIncrement: true
              - column:
                  name: name
                  type: varchar(30)
                  constraints:
                    nullable: false
                    unique: true
        - createTable:
            tableName: users
            columns:
              - column:
                  name: id
                  type: BIGINT
                  constraints:
                    primaryKey: true
                    nullable: false
                    autoIncrement: true
              - column:
                  name: login
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: password
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: role_id
                  type: BIGINT
                  constraints:
                    nullable: false
                    foreignKeyName: fk_role_id
                    references: roles(id)
              - column:
                  name: surname
                  type: VARCHAR(35)
                  constraints:
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(35)
                  constraints:
                    nullable: false
              - column:
                  name: patronymic
                  type: VARCHAR(35)
              - column:
                  name: birthday
                  type: DATE
                  constraints:
                    nullable: false
        - createTable:
            tableName: cards
            columns:
              - column:
                  name: id
                  type: BIGINT
                  constraints:
                    primaryKey: true
                    nullable: false
                    autoIncrement: true
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    nullable: false
                    foreignKeyName: fk_user_id
                    references: users(id)
              - column:
                  name: card_number_encrypted
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: status
                  type: VARCHAR(10)
                  constraints:
                    nullable: false
              - column:
                  name: expiry_date
                  type: DATE
                  constraints:
                    nullable: false
              - column:
                  name: balance
                  type: DECIMAL(15,2)
                  defaultValue: "0.00"
                  constraints:
                    nullable: false
        - createTable:
            tableName: transfers
            columns:
                - column:
                    name: id
                    type: BIGINT
                    constraints:
                      primaryKey: true
                      nullable: false
                      autoIncrement: true
                - column:
                    name: from_card_id
                    type: BIGINT
                    constraints:
                      nullable: false
                      foreignKeyName: fk_from_card_id
                      references: cards(id)
                - column:
                    name: to_card_id
                    type: BIGINT
                    constraints:
                      nullable: false
                      foreignKeyName: fk_to_card_id
                      references: cards(id)
                - column:
                    name: amount
                    type: DECIMAL(15,2)
                    constraints:
                      nullable: false
                - column:
                    name: timestamp
                    type: TIMESTAMP
                    defaultValueComputed: CURRENT_TIMESTAMP
                    constraints:
                      nullable: false
        - addUniqueConstraint:
            constraintName: uk_cards_user_encrypted
            tableName: cards
            columnNames: user_id, card_number_encrypted